import dotenv from "dotenv";
dotenv.config();

import bcrypt from "bcryptjs";
import { connectMongo } from "../config/dbMongo.js";
import { connectPostgres, sequelize } from "../config/dbPostgres.js";
import { Organization } from "../models/sql/Organization.js";
import { User } from "../models/sql/User.js";

// Load models
import "../models/sql/index.js";

(async () => {
    try {
        console.log("🔧 Starting safe seed...");

        await connectMongo();
        await connectPostgres();

        await sequelize.sync({ alter: true });

        // 1. Seed Superadmin
        const superEmail = "superadmin@papdocauthx.com";
        let superadmin = await User.findOne({ where: { email: superEmail } });

        if (!superadmin) {
            const passwordHash = await bcrypt.hash("Admin@123", 10);
            superadmin = await User.create({
                fullName: "Seed Superadmin",
                email: superEmail,
                passwordHash,
                role: "superadmin",
                orgId: null,
            });
            console.log("✔ Superadmin created");
        } else {
            console.log("• Superadmin exists — skipping");
        }

        // 2. Seed Organizations
        const orgSeedData = [
            { name: "University of Windsor", type: "university" },
            { name: "ABC Corporate", type: "company" },
            { name: "Panjab University", type: "university" },
        ];

        const orgRecords = [];

        for (const orgInfo of orgSeedData) {
            let org = await Organization.findOne({ where: { name: orgInfo.name } });

            if (!org) {
                org = await Organization.create({
                    name: orgInfo.name,
                    type: orgInfo.type,
                    // slug is auto-generated by hook
                });
                console.log(`✔ Created organization: ${orgInfo.name}`);
            } else {
                console.log(`• Organization exists: ${orgInfo.name}`);
            }

            orgRecords.push(org);
        }

        // 3. Seed Admins for each org
        for (const org of orgRecords) {
            const email = `${org.name.replaceAll(" ", "").toLowerCase()}@org.com`;

            let admin = await User.findOne({ where: { email } });
            if (!admin) {
                const passwordHash = await bcrypt.hash("Admin@123", 10);

                admin = await User.create({
                    fullName: `${org.name} Admin`,
                    email,
                    passwordHash,
                    role: "admin",
                    orgId: org.id,
                });

                console.log(`✔ Created admin for: ${org.name}`);
            } else {
                console.log(`• Admin exists for: ${org.name}`);
            }
        }

        console.log("🎉 Safe seeding completed.");
        process.exit(0);
    } catch (err) {
        console.error("❌ Seeder error:", err);
        process.exit(1);
    }
})();
